package libraryprojebarrowtable;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

public class BorrowSubmit extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private Label labelBorrowDate;
	private Label labelMemberID;
	private Label labelBookID;
	private Label labelDeadLine;
	private Label labelBorrowID;
	private Label labelBookName;
	private Label labelPersonName;
	
	public BorrowSubmit() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new HorizontalLayout();
		labelBorrowDate=new Label();
		labelMemberID=new Label();
		labelBookID=new Label();
		labelDeadLine=new Label();
		labelBorrowID=new Label();
		labelBookName=new Label();
		labelPersonName=new Label();
		 
		 
		labelBorrowDate.setImmediate(true);
		labelMemberID.setImmediate(true);
		labelBookID.setImmediate(true);
		labelDeadLine.setImmediate(true);
		labelBorrowID.setImmediate(true);
		labelBookName.setImmediate(true);
		labelPersonName.setImmediate(true);
		  
			mainLayout.addComponent(labelBorrowDate);
			mainLayout.addComponent(labelMemberID);
			mainLayout.addComponent(labelBookID);
			mainLayout.addComponent(labelDeadLine);
			mainLayout.addComponent(labelBorrowID);
			mainLayout.addComponent(labelBookName);
			mainLayout.addComponent(labelPersonName);
	}

	public Label getLabelBorrowDate() {
		return labelBorrowDate;
	}

	public void setLabelBorrowDate(Label labelBorrowDate) {
		this.labelBorrowDate = labelBorrowDate;
	}

	public Label getLabelMemberID() {
		return labelMemberID;
	}

	public void setLabelMemberID(Label labelMemberID) {
		this.labelMemberID = labelMemberID;
	}

	public Label getLabelBookID() {
		return labelBookID;
	}

	public void setLabelBookID(Label labelBookID) {
		this.labelBookID = labelBookID;
	}

	public Label getLabelDeadLine() {
		return labelDeadLine;
	}

	public void setLabelDeadLine(Label labelDeadLine) {
		this.labelDeadLine = labelDeadLine;
	}

	public Label getLabelBorrowID() {
		return labelBorrowID;
	}

	public void setLabelBorrowID(Label labelBorrowID) {
		this.labelBorrowID = labelBorrowID;
	}

	public Label getLabelBookName() {
		return labelBookName;
	}

	public void setLabelBookName(Label labelBookName) {
		this.labelBookName = labelBookName;
	}

	public Label getLabelPersonName() {
		return labelPersonName;
	}

	public void setLabelPersonName(Label labelPersonName) {
		this.labelPersonName = labelPersonName;
	}
	

}
