package libraryprojebooktable;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;


public class BookSubmit extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private Label labelBookName;
	private Label labelISBN;
	private Label labelPageNumber;
	private Label labelPubDate;
	private Label labelAuthorName;
	private Label labelAuthorLastName;
	private Label labelBookID;
	private Label labelCategoryName;
	public BookSubmit() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new HorizontalLayout();
		 labelBookName=new Label();
		 labelISBN=new Label();
		 labelPageNumber=new Label();
		 labelPubDate=new Label();
		 labelAuthorName=new Label();
		 labelAuthorLastName=new Label();
		 labelBookID=new Label();
		 labelCategoryName=new Label();
		 
		 labelBookName.setImmediate(true);
		 labelISBN.setImmediate(true);
		 labelPageNumber.setImmediate(true);
		 labelPubDate.setImmediate(true);
		 labelAuthorName.setImmediate(true);
		 labelAuthorLastName.setImmediate(true);
		 labelBookID.setImmediate(true);
		 labelCategoryName.setImmediate(true);
		  
			mainLayout.addComponent(labelBookName);
			mainLayout.addComponent(labelISBN);
			mainLayout.addComponent(labelPageNumber);
			mainLayout.addComponent(labelPubDate);
			mainLayout.addComponent(labelAuthorName);
			mainLayout.addComponent(labelAuthorLastName);
			mainLayout.addComponent(labelBookID);
			mainLayout.addComponent(labelCategoryName);
		
		
	}

	public  Label getLabelBookName() {
		return labelBookName;
	}

	public void setLabelBookName(Label labelBookName) {
		this.labelBookName = labelBookName;
	}

	public Label getLabelISBN() {
		return labelISBN;
	}

	public void setLabelISBN(Label labelAuthorName) {
		this.labelISBN = labelAuthorName;
	}

	public Label getLabelPageNumber() {
		return labelPageNumber;
	}

	public void setLabelPageNumber(Label labelPageNumber) {
		this.labelPageNumber = labelPageNumber;
	}

	public Label getLabelPubDate() {
		return labelPubDate;
	}

	public void setLabelPubDate(Label labelPubDate) {
		this.labelPubDate = labelPubDate;
	}

	public Label getLabelAuthorName() {
		return labelAuthorName;
	}

	public void setLabelAuthorName(Label labelAuthorName) {
		this.labelAuthorName = labelAuthorName;
	}

	public Label getLabelAuthorLastName() {
		return labelAuthorLastName;
	}

	public void setLabelAuthorLastName(Label labelAuthorLastName) {
		this.labelAuthorLastName = labelAuthorLastName;
	}

	public Label getLabelBookID() {
		return labelBookID;
	}

	public void setLabelBookID(Label labelBookID) {
		this.labelBookID = labelBookID;
	}

	public Label getLabelCategoryName() {
		return labelCategoryName;
	}

	public void setLabelCategoryName(Label labelCategoryName) {
		this.labelCategoryName = labelCategoryName;
	}

}