package libraryprojebooktable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class VeriCekme extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VeriCekme() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		mainLayout = new VerticalLayout();
		
		  Connection con = null;
			try {
				con = DriverManager.getConnection
						  ( "jdbc:oracle:thin:@localhost:1521:XE", "YBUORCL","ybu123");
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

			  
			  Statement ifade = null;
			try {
				ifade = con.createStatement();
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			  ResultSet sonucKumesi = null;
			try {
				sonucKumesi = ifade.executeQuery("SELECT * FROM Book");
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			  int i=1;
	 	 
				  
			mainLayout.setMargin(true);
			setParent(mainLayout);
			Table table = new Table("The Brightest Stars");

			// Define two columns for the built-in container
//			table.addContainerProperty("Id", Integer.class, 0);
//			table.addContainerProperty("Name",  String.class, null);
			
			table.addContainerProperty("Sum",            Label.class,     null);
//			Label label;
//			 try {
				try {
					while(sonucKumesi.next()){
					 Label label = null;
					try {
						label = new Label(sonucKumesi.getString(2));
					} catch (SQLException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
						 table.addItem(new Object[] {label},2);
						
					}
				} catch (UnsupportedOperationException | SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	}

}
