#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruOnergeleriTakipSistemiCalısma
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SorguOnergeleri")]
	public partial class OnergeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKullanicilar(Kullanicilar instance);
    partial void UpdateKullanicilar(Kullanicilar instance);
    partial void DeleteKullanicilar(Kullanicilar instance);
    partial void InsertGKurum(GKurum instance);
    partial void UpdateGKurum(GKurum instance);
    partial void DeleteGKurum(GKurum instance);
    partial void InsertDurum(Durum instance);
    partial void UpdateDurum(Durum instance);
    partial void DeleteDurum(Durum instance);
    partial void InsertMesaj(Mesaj instance);
    partial void UpdateMesaj(Mesaj instance);
    partial void DeleteMesaj(Mesaj instance);
    partial void InsertKurum(Kurum instance);
    partial void UpdateKurum(Kurum instance);
    partial void DeleteKurum(Kurum instance);
    partial void InsertYöneticiler(Yöneticiler instance);
    partial void UpdateYöneticiler(Yöneticiler instance);
    partial void DeleteYöneticiler(Yöneticiler instance);
    partial void InsertOnergeTuru(OnergeTuru instance);
    partial void UpdateOnergeTuru(OnergeTuru instance);
    partial void DeleteOnergeTuru(OnergeTuru instance);
    partial void InsertOnergeKonuGrupları(OnergeKonuGrupları instance);
    partial void UpdateOnergeKonuGrupları(OnergeKonuGrupları instance);
    partial void DeleteOnergeKonuGrupları(OnergeKonuGrupları instance);
    partial void InsertCevap(Cevap instance);
    partial void UpdateCevap(Cevap instance);
    partial void DeleteCevap(Cevap instance);
    partial void InsertOnerge(Onerge instance);
    partial void UpdateOnerge(Onerge instance);
    partial void DeleteOnerge(Onerge instance);
    partial void InsertMilletVekili(MilletVekili instance);
    partial void UpdateMilletVekili(MilletVekili instance);
    partial void DeleteMilletVekili(MilletVekili instance);
    partial void InsertMesajAdmin(MesajAdmin instance);
    partial void UpdateMesajAdmin(MesajAdmin instance);
    partial void DeleteMesajAdmin(MesajAdmin instance);
    #endregion
		
		public OnergeDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SorguOnergeleriConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OnergeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnergeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnergeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnergeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kullanicilar> Kullanicilars
		{
			get
			{
				return this.GetTable<Kullanicilar>();
			}
		}
		
		public System.Data.Linq.Table<GKurum> GKurums
		{
			get
			{
				return this.GetTable<GKurum>();
			}
		}
		
		public System.Data.Linq.Table<Durum> Durums
		{
			get
			{
				return this.GetTable<Durum>();
			}
		}
		
		public System.Data.Linq.Table<Mesaj> Mesajs
		{
			get
			{
				return this.GetTable<Mesaj>();
			}
		}
		
		public System.Data.Linq.Table<Kurum> Kurums
		{
			get
			{
				return this.GetTable<Kurum>();
			}
		}
		
		public System.Data.Linq.Table<Yöneticiler> Yöneticilers
		{
			get
			{
				return this.GetTable<Yöneticiler>();
			}
		}
		
		public System.Data.Linq.Table<OnergeTuru> OnergeTurus
		{
			get
			{
				return this.GetTable<OnergeTuru>();
			}
		}
		
		public System.Data.Linq.Table<OnergeKonuGrupları> OnergeKonuGruplarıs
		{
			get
			{
				return this.GetTable<OnergeKonuGrupları>();
			}
		}
		
		public System.Data.Linq.Table<Cevap> Cevaps
		{
			get
			{
				return this.GetTable<Cevap>();
			}
		}
		
		public System.Data.Linq.Table<Onerge> Onerges
		{
			get
			{
				return this.GetTable<Onerge>();
			}
		}
		
		public System.Data.Linq.Table<MilletVekili> MilletVekilis
		{
			get
			{
				return this.GetTable<MilletVekili>();
			}
		}
		
		public System.Data.Linq.Table<MesajAdmin> MesajAdmins
		{
			get
			{
				return this.GetTable<MesajAdmin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanicilar")]
	public partial class Kullanicilar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
		private System.Nullable<int> _KurumID;
		
		private string _Email;
		
		private string _Adi;
		
		private string _Soyadi;
		
		private EntityRef<Kurum> _Kurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnKurumIDChanging(System.Nullable<int> value);
    partial void OnKurumIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnSoyadiChanging(string value);
    partial void OnSoyadiChanged();
    #endregion
		
		public Kullanicilar()
		{
			this._Kurum = default(EntityRef<Kurum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(50)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KurumID", DbType="Int")]
		public System.Nullable<int> KurumID
		{
			get
			{
				return this._KurumID;
			}
			set
			{
				if ((this._KurumID != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKurumIDChanging(value);
					this.SendPropertyChanging();
					this._KurumID = value;
					this.SendPropertyChanged("KurumID");
					this.OnKurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyadi", DbType="NVarChar(50)")]
		public string Soyadi
		{
			get
			{
				return this._Soyadi;
			}
			set
			{
				if ((this._Soyadi != value))
				{
					this.OnSoyadiChanging(value);
					this.SendPropertyChanging();
					this._Soyadi = value;
					this.SendPropertyChanged("Soyadi");
					this.OnSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Kullanicilar", Storage="_Kurum", ThisKey="KurumID", OtherKey="ID", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.Kullanicilars.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.Kullanicilars.Add(this);
						this._KurumID = value.ID;
					}
					else
					{
						this._KurumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GKurum")]
	public partial class GKurum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GeldigiKurumAdi;
		
		private EntitySet<Onerge> _Onerges;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGeldigiKurumAdiChanging(string value);
    partial void OnGeldigiKurumAdiChanged();
    #endregion
		
		public GKurum()
		{
			this._Onerges = new EntitySet<Onerge>(new Action<Onerge>(this.attach_Onerges), new Action<Onerge>(this.detach_Onerges));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeldigiKurumAdi", DbType="NVarChar(250)")]
		public string GeldigiKurumAdi
		{
			get
			{
				return this._GeldigiKurumAdi;
			}
			set
			{
				if ((this._GeldigiKurumAdi != value))
				{
					this.OnGeldigiKurumAdiChanging(value);
					this.SendPropertyChanging();
					this._GeldigiKurumAdi = value;
					this.SendPropertyChanged("GeldigiKurumAdi");
					this.OnGeldigiKurumAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GKurum_Onerge", Storage="_Onerges", ThisKey="ID", OtherKey="GeldigiKurumID")]
		public EntitySet<Onerge> Onerges
		{
			get
			{
				return this._Onerges;
			}
			set
			{
				this._Onerges.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.GKurum = this;
		}
		
		private void detach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.GKurum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Durum")]
	public partial class Durum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Durum1;
		
		private EntitySet<Onerge> _Onerges;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDurum1Changing(string value);
    partial void OnDurum1Changed();
    #endregion
		
		public Durum()
		{
			this._Onerges = new EntitySet<Onerge>(new Action<Onerge>(this.attach_Onerges), new Action<Onerge>(this.detach_Onerges));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Durum", Storage="_Durum1", DbType="NVarChar(150)")]
		public string Durum1
		{
			get
			{
				return this._Durum1;
			}
			set
			{
				if ((this._Durum1 != value))
				{
					this.OnDurum1Changing(value);
					this.SendPropertyChanging();
					this._Durum1 = value;
					this.SendPropertyChanged("Durum1");
					this.OnDurum1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Durum_Onerge", Storage="_Onerges", ThisKey="ID", OtherKey="durumID")]
		public EntitySet<Onerge> Onerges
		{
			get
			{
				return this._Onerges;
			}
			set
			{
				this._Onerges.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.Durum = this;
		}
		
		private void detach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.Durum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mesaj")]
	public partial class Mesaj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDM;
		
		private string _mesajKonusu;
		
		private System.Nullable<int> _kurumID;
		
		private System.Nullable<int> _onergeID;
		
		private System.Nullable<int> _kullaniciID;
		
		private System.Nullable<int> _okunma;
		
		private EntityRef<Kurum> _Kurum;
		
		private EntityRef<Onerge> _Onerge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMChanging(int value);
    partial void OnIDMChanged();
    partial void OnmesajKonusuChanging(string value);
    partial void OnmesajKonusuChanged();
    partial void OnkurumIDChanging(System.Nullable<int> value);
    partial void OnkurumIDChanged();
    partial void OnonergeIDChanging(System.Nullable<int> value);
    partial void OnonergeIDChanged();
    partial void OnkullaniciIDChanging(System.Nullable<int> value);
    partial void OnkullaniciIDChanged();
    partial void OnokunmaChanging(System.Nullable<int> value);
    partial void OnokunmaChanged();
    #endregion
		
		public Mesaj()
		{
			this._Kurum = default(EntityRef<Kurum>);
			this._Onerge = default(EntityRef<Onerge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDM
		{
			get
			{
				return this._IDM;
			}
			set
			{
				if ((this._IDM != value))
				{
					this.OnIDMChanging(value);
					this.SendPropertyChanging();
					this._IDM = value;
					this.SendPropertyChanged("IDM");
					this.OnIDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesajKonusu", DbType="NVarChar(50)")]
		public string mesajKonusu
		{
			get
			{
				return this._mesajKonusu;
			}
			set
			{
				if ((this._mesajKonusu != value))
				{
					this.OnmesajKonusuChanging(value);
					this.SendPropertyChanging();
					this._mesajKonusu = value;
					this.SendPropertyChanged("mesajKonusu");
					this.OnmesajKonusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurumID", DbType="Int")]
		public System.Nullable<int> kurumID
		{
			get
			{
				return this._kurumID;
			}
			set
			{
				if ((this._kurumID != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkurumIDChanging(value);
					this.SendPropertyChanging();
					this._kurumID = value;
					this.SendPropertyChanged("kurumID");
					this.OnkurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onergeID", DbType="Int")]
		public System.Nullable<int> onergeID
		{
			get
			{
				return this._onergeID;
			}
			set
			{
				if ((this._onergeID != value))
				{
					if (this._Onerge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnonergeIDChanging(value);
					this.SendPropertyChanging();
					this._onergeID = value;
					this.SendPropertyChanged("onergeID");
					this.OnonergeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciID", DbType="Int")]
		public System.Nullable<int> kullaniciID
		{
			get
			{
				return this._kullaniciID;
			}
			set
			{
				if ((this._kullaniciID != value))
				{
					this.OnkullaniciIDChanging(value);
					this.SendPropertyChanging();
					this._kullaniciID = value;
					this.SendPropertyChanged("kullaniciID");
					this.OnkullaniciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okunma", DbType="Int")]
		public System.Nullable<int> okunma
		{
			get
			{
				return this._okunma;
			}
			set
			{
				if ((this._okunma != value))
				{
					this.OnokunmaChanging(value);
					this.SendPropertyChanging();
					this._okunma = value;
					this.SendPropertyChanged("okunma");
					this.OnokunmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Mesaj", Storage="_Kurum", ThisKey="kurumID", OtherKey="ID", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.Mesajs.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.Mesajs.Add(this);
						this._kurumID = value.ID;
					}
					else
					{
						this._kurumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Onerge_Mesaj", Storage="_Onerge", ThisKey="onergeID", OtherKey="ID", IsForeignKey=true)]
		public Onerge Onerge
		{
			get
			{
				return this._Onerge.Entity;
			}
			set
			{
				Onerge previousValue = this._Onerge.Entity;
				if (((previousValue != value) 
							|| (this._Onerge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Onerge.Entity = null;
						previousValue.Mesajs.Remove(this);
					}
					this._Onerge.Entity = value;
					if ((value != null))
					{
						value.Mesajs.Add(this);
						this._onergeID = value.ID;
					}
					else
					{
						this._onergeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Onerge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kurum")]
	public partial class Kurum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KurumAd;
		
		private EntitySet<Kullanicilar> _Kullanicilars;
		
		private EntitySet<Mesaj> _Mesajs;
		
		private EntitySet<Yöneticiler> _Yöneticilers;
		
		private EntitySet<Cevap> _Cevaps;
		
		private EntitySet<Onerge> _Onerges;
		
		private EntitySet<MesajAdmin> _MesajAdmins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKurumAdChanging(string value);
    partial void OnKurumAdChanged();
    #endregion
		
		public Kurum()
		{
			this._Kullanicilars = new EntitySet<Kullanicilar>(new Action<Kullanicilar>(this.attach_Kullanicilars), new Action<Kullanicilar>(this.detach_Kullanicilars));
			this._Mesajs = new EntitySet<Mesaj>(new Action<Mesaj>(this.attach_Mesajs), new Action<Mesaj>(this.detach_Mesajs));
			this._Yöneticilers = new EntitySet<Yöneticiler>(new Action<Yöneticiler>(this.attach_Yöneticilers), new Action<Yöneticiler>(this.detach_Yöneticilers));
			this._Cevaps = new EntitySet<Cevap>(new Action<Cevap>(this.attach_Cevaps), new Action<Cevap>(this.detach_Cevaps));
			this._Onerges = new EntitySet<Onerge>(new Action<Onerge>(this.attach_Onerges), new Action<Onerge>(this.detach_Onerges));
			this._MesajAdmins = new EntitySet<MesajAdmin>(new Action<MesajAdmin>(this.attach_MesajAdmins), new Action<MesajAdmin>(this.detach_MesajAdmins));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KurumAd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KurumAd
		{
			get
			{
				return this._KurumAd;
			}
			set
			{
				if ((this._KurumAd != value))
				{
					this.OnKurumAdChanging(value);
					this.SendPropertyChanging();
					this._KurumAd = value;
					this.SendPropertyChanged("KurumAd");
					this.OnKurumAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Kullanicilar", Storage="_Kullanicilars", ThisKey="ID", OtherKey="KurumID")]
		public EntitySet<Kullanicilar> Kullanicilars
		{
			get
			{
				return this._Kullanicilars;
			}
			set
			{
				this._Kullanicilars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Mesaj", Storage="_Mesajs", ThisKey="ID", OtherKey="kurumID")]
		public EntitySet<Mesaj> Mesajs
		{
			get
			{
				return this._Mesajs;
			}
			set
			{
				this._Mesajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Yöneticiler", Storage="_Yöneticilers", ThisKey="ID", OtherKey="KurumID")]
		public EntitySet<Yöneticiler> Yöneticilers
		{
			get
			{
				return this._Yöneticilers;
			}
			set
			{
				this._Yöneticilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Cevap", Storage="_Cevaps", ThisKey="ID", OtherKey="kurumID")]
		public EntitySet<Cevap> Cevaps
		{
			get
			{
				return this._Cevaps;
			}
			set
			{
				this._Cevaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Onerge", Storage="_Onerges", ThisKey="ID", OtherKey="kurumID")]
		public EntitySet<Onerge> Onerges
		{
			get
			{
				return this._Onerges;
			}
			set
			{
				this._Onerges.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_MesajAdmin", Storage="_MesajAdmins", ThisKey="ID", OtherKey="kurumID")]
		public EntitySet<MesajAdmin> MesajAdmins
		{
			get
			{
				return this._MesajAdmins;
			}
			set
			{
				this._MesajAdmins.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Kullanicilars(Kullanicilar entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_Kullanicilars(Kullanicilar entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
		
		private void attach_Mesajs(Mesaj entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_Mesajs(Mesaj entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
		
		private void attach_Yöneticilers(Yöneticiler entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_Yöneticilers(Yöneticiler entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
		
		private void attach_Cevaps(Cevap entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_Cevaps(Cevap entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
		
		private void attach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
		
		private void attach_MesajAdmins(MesajAdmin entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = this;
		}
		
		private void detach_MesajAdmins(MesajAdmin entity)
		{
			this.SendPropertyChanging();
			entity.Kurum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yöneticiler")]
	public partial class Yöneticiler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _kullaniciAdi;
		
		private string _Sifre;
		
		private string _Email;
		
		private string _adi;
		
		private string _soyadi;
		
		private System.Nullable<int> _KurumID;
		
		private EntityRef<Kurum> _Kurum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnkullaniciAdiChanging(string value);
    partial void OnkullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OnKurumIDChanging(System.Nullable<int> value);
    partial void OnKurumIDChanged();
    #endregion
		
		public Yöneticiler()
		{
			this._Kurum = default(EntityRef<Kurum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciAdi", DbType="NVarChar(50)")]
		public string kullaniciAdi
		{
			get
			{
				return this._kullaniciAdi;
			}
			set
			{
				if ((this._kullaniciAdi != value))
				{
					this.OnkullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._kullaniciAdi = value;
					this.SendPropertyChanged("kullaniciAdi");
					this.OnkullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="NVarChar(50)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="NVarChar(50)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KurumID", DbType="Int")]
		public System.Nullable<int> KurumID
		{
			get
			{
				return this._KurumID;
			}
			set
			{
				if ((this._KurumID != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKurumIDChanging(value);
					this.SendPropertyChanging();
					this._KurumID = value;
					this.SendPropertyChanged("KurumID");
					this.OnKurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Yöneticiler", Storage="_Kurum", ThisKey="KurumID", OtherKey="ID", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.Yöneticilers.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.Yöneticilers.Add(this);
						this._KurumID = value.ID;
					}
					else
					{
						this._KurumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnergeTuru")]
	public partial class OnergeTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TürAdı;
		
		private EntitySet<Onerge> _Onerges;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTürAdıChanging(string value);
    partial void OnTürAdıChanged();
    #endregion
		
		public OnergeTuru()
		{
			this._Onerges = new EntitySet<Onerge>(new Action<Onerge>(this.attach_Onerges), new Action<Onerge>(this.detach_Onerges));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TürAdı", DbType="NVarChar(MAX)")]
		public string TürAdı
		{
			get
			{
				return this._TürAdı;
			}
			set
			{
				if ((this._TürAdı != value))
				{
					this.OnTürAdıChanging(value);
					this.SendPropertyChanging();
					this._TürAdı = value;
					this.SendPropertyChanged("TürAdı");
					this.OnTürAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnergeTuru_Onerge", Storage="_Onerges", ThisKey="ID", OtherKey="TurID")]
		public EntitySet<Onerge> Onerges
		{
			get
			{
				return this._Onerges;
			}
			set
			{
				this._Onerges.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.OnergeTuru = this;
		}
		
		private void detach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.OnergeTuru = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnergeKonuGrupları")]
	public partial class OnergeKonuGrupları : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OnergeKonusu;
		
		private System.Nullable<int> _KonuSayısı;
		
		private EntitySet<Onerge> _Onerges;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOnergeKonusuChanging(string value);
    partial void OnOnergeKonusuChanged();
    partial void OnKonuSayısıChanging(System.Nullable<int> value);
    partial void OnKonuSayısıChanged();
    #endregion
		
		public OnergeKonuGrupları()
		{
			this._Onerges = new EntitySet<Onerge>(new Action<Onerge>(this.attach_Onerges), new Action<Onerge>(this.detach_Onerges));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnergeKonusu", DbType="NVarChar(MAX)")]
		public string OnergeKonusu
		{
			get
			{
				return this._OnergeKonusu;
			}
			set
			{
				if ((this._OnergeKonusu != value))
				{
					this.OnOnergeKonusuChanging(value);
					this.SendPropertyChanging();
					this._OnergeKonusu = value;
					this.SendPropertyChanged("OnergeKonusu");
					this.OnOnergeKonusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KonuSayısı", DbType="Int")]
		public System.Nullable<int> KonuSayısı
		{
			get
			{
				return this._KonuSayısı;
			}
			set
			{
				if ((this._KonuSayısı != value))
				{
					this.OnKonuSayısıChanging(value);
					this.SendPropertyChanging();
					this._KonuSayısı = value;
					this.SendPropertyChanged("KonuSayısı");
					this.OnKonuSayısıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnergeKonuGrupları_Onerge", Storage="_Onerges", ThisKey="ID", OtherKey="KonuGrupID")]
		public EntitySet<Onerge> Onerges
		{
			get
			{
				return this._Onerges;
			}
			set
			{
				this._Onerges.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.OnergeKonuGrupları = this;
		}
		
		private void detach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.OnergeKonuGrupları = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cevap")]
	public partial class Cevap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CevapID;
		
		private string _uzanti;
		
		private System.Nullable<int> _durumID;
		
		private System.Nullable<int> _onergeID;
		
		private System.Nullable<int> _kurumID;
		
		private EntityRef<Kurum> _Kurum;
		
		private EntityRef<Onerge> _Onerge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCevapIDChanging(int value);
    partial void OnCevapIDChanged();
    partial void OnuzantiChanging(string value);
    partial void OnuzantiChanged();
    partial void OndurumIDChanging(System.Nullable<int> value);
    partial void OndurumIDChanged();
    partial void OnonergeIDChanging(System.Nullable<int> value);
    partial void OnonergeIDChanged();
    partial void OnkurumIDChanging(System.Nullable<int> value);
    partial void OnkurumIDChanged();
    #endregion
		
		public Cevap()
		{
			this._Kurum = default(EntityRef<Kurum>);
			this._Onerge = default(EntityRef<Onerge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CevapID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CevapID
		{
			get
			{
				return this._CevapID;
			}
			set
			{
				if ((this._CevapID != value))
				{
					this.OnCevapIDChanging(value);
					this.SendPropertyChanging();
					this._CevapID = value;
					this.SendPropertyChanged("CevapID");
					this.OnCevapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uzanti", DbType="NVarChar(MAX)")]
		public string uzanti
		{
			get
			{
				return this._uzanti;
			}
			set
			{
				if ((this._uzanti != value))
				{
					this.OnuzantiChanging(value);
					this.SendPropertyChanging();
					this._uzanti = value;
					this.SendPropertyChanged("uzanti");
					this.OnuzantiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durumID", DbType="Int")]
		public System.Nullable<int> durumID
		{
			get
			{
				return this._durumID;
			}
			set
			{
				if ((this._durumID != value))
				{
					this.OndurumIDChanging(value);
					this.SendPropertyChanging();
					this._durumID = value;
					this.SendPropertyChanged("durumID");
					this.OndurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onergeID", DbType="Int")]
		public System.Nullable<int> onergeID
		{
			get
			{
				return this._onergeID;
			}
			set
			{
				if ((this._onergeID != value))
				{
					if (this._Onerge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnonergeIDChanging(value);
					this.SendPropertyChanging();
					this._onergeID = value;
					this.SendPropertyChanged("onergeID");
					this.OnonergeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurumID", DbType="Int")]
		public System.Nullable<int> kurumID
		{
			get
			{
				return this._kurumID;
			}
			set
			{
				if ((this._kurumID != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkurumIDChanging(value);
					this.SendPropertyChanging();
					this._kurumID = value;
					this.SendPropertyChanged("kurumID");
					this.OnkurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Cevap", Storage="_Kurum", ThisKey="kurumID", OtherKey="ID", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.Cevaps.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.Cevaps.Add(this);
						this._kurumID = value.ID;
					}
					else
					{
						this._kurumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Onerge_Cevap", Storage="_Onerge", ThisKey="onergeID", OtherKey="ID", IsForeignKey=true)]
		public Onerge Onerge
		{
			get
			{
				return this._Onerge.Entity;
			}
			set
			{
				Onerge previousValue = this._Onerge.Entity;
				if (((previousValue != value) 
							|| (this._Onerge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Onerge.Entity = null;
						previousValue.Cevaps.Remove(this);
					}
					this._Onerge.Entity = value;
					if ((value != null))
					{
						value.Cevaps.Add(this);
						this._onergeID = value.ID;
					}
					else
					{
						this._onergeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Onerge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Onerge")]
	public partial class Onerge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Donem;
		
		private System.Nullable<int> _YasamaYili;
		
		private System.Nullable<int> _EsasNo;
		
		private string _MilletvekilAdi;
		
		private string _MilletvekilPartisiIli;
		
		private System.Nullable<System.DateTime> _EvrakTarihi;
		
		private string _OnergeKonusu;
		
		private string _Extension;
		
		private System.Nullable<int> _kurumID;
		
		private System.Nullable<int> _GeldigiKurumID;
		
		private System.Nullable<int> _KullanıcıID;
		
		private System.Nullable<int> _durumID;
		
		private System.Nullable<int> _milletvekiliID;
		
		private System.Nullable<int> _TurID;
		
		private System.Nullable<int> _KonuGrupID;
		
		private System.Nullable<System.DateTime> _BitisTarihi;
		
		private EntitySet<Mesaj> _Mesajs;
		
		private EntitySet<Cevap> _Cevaps;
		
		private EntitySet<MesajAdmin> _MesajAdmins;
		
		private EntityRef<Durum> _Durum;
		
		private EntityRef<GKurum> _GKurum;
		
		private EntityRef<Kurum> _Kurum;
		
		private EntityRef<OnergeKonuGrupları> _OnergeKonuGrupları;
		
		private EntityRef<OnergeTuru> _OnergeTuru;
		
		private EntityRef<MilletVekili> _MilletVekili;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDonemChanging(System.Nullable<int> value);
    partial void OnDonemChanged();
    partial void OnYasamaYiliChanging(System.Nullable<int> value);
    partial void OnYasamaYiliChanged();
    partial void OnEsasNoChanging(System.Nullable<int> value);
    partial void OnEsasNoChanged();
    partial void OnMilletvekilAdiChanging(string value);
    partial void OnMilletvekilAdiChanged();
    partial void OnMilletvekilPartisiIliChanging(string value);
    partial void OnMilletvekilPartisiIliChanged();
    partial void OnEvrakTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnEvrakTarihiChanged();
    partial void OnOnergeKonusuChanging(string value);
    partial void OnOnergeKonusuChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnkurumIDChanging(System.Nullable<int> value);
    partial void OnkurumIDChanged();
    partial void OnGeldigiKurumIDChanging(System.Nullable<int> value);
    partial void OnGeldigiKurumIDChanged();
    partial void OnKullanıcıIDChanging(System.Nullable<int> value);
    partial void OnKullanıcıIDChanged();
    partial void OndurumIDChanging(System.Nullable<int> value);
    partial void OndurumIDChanged();
    partial void OnmilletvekiliIDChanging(System.Nullable<int> value);
    partial void OnmilletvekiliIDChanged();
    partial void OnTurIDChanging(System.Nullable<int> value);
    partial void OnTurIDChanged();
    partial void OnKonuGrupIDChanging(System.Nullable<int> value);
    partial void OnKonuGrupIDChanged();
    partial void OnBitisTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnBitisTarihiChanged();
    #endregion
		
		public Onerge()
		{
			this._Mesajs = new EntitySet<Mesaj>(new Action<Mesaj>(this.attach_Mesajs), new Action<Mesaj>(this.detach_Mesajs));
			this._Cevaps = new EntitySet<Cevap>(new Action<Cevap>(this.attach_Cevaps), new Action<Cevap>(this.detach_Cevaps));
			this._MesajAdmins = new EntitySet<MesajAdmin>(new Action<MesajAdmin>(this.attach_MesajAdmins), new Action<MesajAdmin>(this.detach_MesajAdmins));
			this._Durum = default(EntityRef<Durum>);
			this._GKurum = default(EntityRef<GKurum>);
			this._Kurum = default(EntityRef<Kurum>);
			this._OnergeKonuGrupları = default(EntityRef<OnergeKonuGrupları>);
			this._OnergeTuru = default(EntityRef<OnergeTuru>);
			this._MilletVekili = default(EntityRef<MilletVekili>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donem", DbType="Int")]
		public System.Nullable<int> Donem
		{
			get
			{
				return this._Donem;
			}
			set
			{
				if ((this._Donem != value))
				{
					this.OnDonemChanging(value);
					this.SendPropertyChanging();
					this._Donem = value;
					this.SendPropertyChanged("Donem");
					this.OnDonemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YasamaYili", DbType="Int")]
		public System.Nullable<int> YasamaYili
		{
			get
			{
				return this._YasamaYili;
			}
			set
			{
				if ((this._YasamaYili != value))
				{
					this.OnYasamaYiliChanging(value);
					this.SendPropertyChanging();
					this._YasamaYili = value;
					this.SendPropertyChanged("YasamaYili");
					this.OnYasamaYiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsasNo", DbType="Int")]
		public System.Nullable<int> EsasNo
		{
			get
			{
				return this._EsasNo;
			}
			set
			{
				if ((this._EsasNo != value))
				{
					this.OnEsasNoChanging(value);
					this.SendPropertyChanging();
					this._EsasNo = value;
					this.SendPropertyChanged("EsasNo");
					this.OnEsasNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilletvekilAdi", DbType="NVarChar(50)")]
		public string MilletvekilAdi
		{
			get
			{
				return this._MilletvekilAdi;
			}
			set
			{
				if ((this._MilletvekilAdi != value))
				{
					this.OnMilletvekilAdiChanging(value);
					this.SendPropertyChanging();
					this._MilletvekilAdi = value;
					this.SendPropertyChanged("MilletvekilAdi");
					this.OnMilletvekilAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MilletvekilPartisiIli", DbType="NVarChar(50)")]
		public string MilletvekilPartisiIli
		{
			get
			{
				return this._MilletvekilPartisiIli;
			}
			set
			{
				if ((this._MilletvekilPartisiIli != value))
				{
					this.OnMilletvekilPartisiIliChanging(value);
					this.SendPropertyChanging();
					this._MilletvekilPartisiIli = value;
					this.SendPropertyChanged("MilletvekilPartisiIli");
					this.OnMilletvekilPartisiIliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvrakTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> EvrakTarihi
		{
			get
			{
				return this._EvrakTarihi;
			}
			set
			{
				if ((this._EvrakTarihi != value))
				{
					this.OnEvrakTarihiChanging(value);
					this.SendPropertyChanging();
					this._EvrakTarihi = value;
					this.SendPropertyChanged("EvrakTarihi");
					this.OnEvrakTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnergeKonusu", DbType="NVarChar(MAX)")]
		public string OnergeKonusu
		{
			get
			{
				return this._OnergeKonusu;
			}
			set
			{
				if ((this._OnergeKonusu != value))
				{
					this.OnOnergeKonusuChanging(value);
					this.SendPropertyChanging();
					this._OnergeKonusu = value;
					this.SendPropertyChanged("OnergeKonusu");
					this.OnOnergeKonusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="NVarChar(150)")]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurumID", DbType="Int")]
		public System.Nullable<int> kurumID
		{
			get
			{
				return this._kurumID;
			}
			set
			{
				if ((this._kurumID != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkurumIDChanging(value);
					this.SendPropertyChanging();
					this._kurumID = value;
					this.SendPropertyChanged("kurumID");
					this.OnkurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeldigiKurumID", DbType="Int")]
		public System.Nullable<int> GeldigiKurumID
		{
			get
			{
				return this._GeldigiKurumID;
			}
			set
			{
				if ((this._GeldigiKurumID != value))
				{
					if (this._GKurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGeldigiKurumIDChanging(value);
					this.SendPropertyChanging();
					this._GeldigiKurumID = value;
					this.SendPropertyChanged("GeldigiKurumID");
					this.OnGeldigiKurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullanıcıID", DbType="Int")]
		public System.Nullable<int> KullanıcıID
		{
			get
			{
				return this._KullanıcıID;
			}
			set
			{
				if ((this._KullanıcıID != value))
				{
					this.OnKullanıcıIDChanging(value);
					this.SendPropertyChanging();
					this._KullanıcıID = value;
					this.SendPropertyChanged("KullanıcıID");
					this.OnKullanıcıIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durumID", DbType="Int")]
		public System.Nullable<int> durumID
		{
			get
			{
				return this._durumID;
			}
			set
			{
				if ((this._durumID != value))
				{
					if (this._Durum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndurumIDChanging(value);
					this.SendPropertyChanging();
					this._durumID = value;
					this.SendPropertyChanged("durumID");
					this.OndurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_milletvekiliID", DbType="Int")]
		public System.Nullable<int> milletvekiliID
		{
			get
			{
				return this._milletvekiliID;
			}
			set
			{
				if ((this._milletvekiliID != value))
				{
					if (this._MilletVekili.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmilletvekiliIDChanging(value);
					this.SendPropertyChanging();
					this._milletvekiliID = value;
					this.SendPropertyChanged("milletvekiliID");
					this.OnmilletvekiliIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TurID", DbType="Int")]
		public System.Nullable<int> TurID
		{
			get
			{
				return this._TurID;
			}
			set
			{
				if ((this._TurID != value))
				{
					if (this._OnergeTuru.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTurIDChanging(value);
					this.SendPropertyChanging();
					this._TurID = value;
					this.SendPropertyChanged("TurID");
					this.OnTurIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KonuGrupID", DbType="Int")]
		public System.Nullable<int> KonuGrupID
		{
			get
			{
				return this._KonuGrupID;
			}
			set
			{
				if ((this._KonuGrupID != value))
				{
					if (this._OnergeKonuGrupları.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKonuGrupIDChanging(value);
					this.SendPropertyChanging();
					this._KonuGrupID = value;
					this.SendPropertyChanged("KonuGrupID");
					this.OnKonuGrupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> BitisTarihi
		{
			get
			{
				return this._BitisTarihi;
			}
			set
			{
				if ((this._BitisTarihi != value))
				{
					this.OnBitisTarihiChanging(value);
					this.SendPropertyChanging();
					this._BitisTarihi = value;
					this.SendPropertyChanged("BitisTarihi");
					this.OnBitisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Onerge_Mesaj", Storage="_Mesajs", ThisKey="ID", OtherKey="onergeID")]
		public EntitySet<Mesaj> Mesajs
		{
			get
			{
				return this._Mesajs;
			}
			set
			{
				this._Mesajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Onerge_Cevap", Storage="_Cevaps", ThisKey="ID", OtherKey="onergeID")]
		public EntitySet<Cevap> Cevaps
		{
			get
			{
				return this._Cevaps;
			}
			set
			{
				this._Cevaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Onerge_MesajAdmin", Storage="_MesajAdmins", ThisKey="ID", OtherKey="onergeID")]
		public EntitySet<MesajAdmin> MesajAdmins
		{
			get
			{
				return this._MesajAdmins;
			}
			set
			{
				this._MesajAdmins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Durum_Onerge", Storage="_Durum", ThisKey="durumID", OtherKey="ID", IsForeignKey=true)]
		public Durum Durum
		{
			get
			{
				return this._Durum.Entity;
			}
			set
			{
				Durum previousValue = this._Durum.Entity;
				if (((previousValue != value) 
							|| (this._Durum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Durum.Entity = null;
						previousValue.Onerges.Remove(this);
					}
					this._Durum.Entity = value;
					if ((value != null))
					{
						value.Onerges.Add(this);
						this._durumID = value.ID;
					}
					else
					{
						this._durumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Durum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GKurum_Onerge", Storage="_GKurum", ThisKey="GeldigiKurumID", OtherKey="ID", IsForeignKey=true)]
		public GKurum GKurum
		{
			get
			{
				return this._GKurum.Entity;
			}
			set
			{
				GKurum previousValue = this._GKurum.Entity;
				if (((previousValue != value) 
							|| (this._GKurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GKurum.Entity = null;
						previousValue.Onerges.Remove(this);
					}
					this._GKurum.Entity = value;
					if ((value != null))
					{
						value.Onerges.Add(this);
						this._GeldigiKurumID = value.ID;
					}
					else
					{
						this._GeldigiKurumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("GKurum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_Onerge", Storage="_Kurum", ThisKey="kurumID", OtherKey="ID", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.Onerges.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.Onerges.Add(this);
						this._kurumID = value.ID;
					}
					else
					{
						this._kurumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnergeKonuGrupları_Onerge", Storage="_OnergeKonuGrupları", ThisKey="KonuGrupID", OtherKey="ID", IsForeignKey=true)]
		public OnergeKonuGrupları OnergeKonuGrupları
		{
			get
			{
				return this._OnergeKonuGrupları.Entity;
			}
			set
			{
				OnergeKonuGrupları previousValue = this._OnergeKonuGrupları.Entity;
				if (((previousValue != value) 
							|| (this._OnergeKonuGrupları.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OnergeKonuGrupları.Entity = null;
						previousValue.Onerges.Remove(this);
					}
					this._OnergeKonuGrupları.Entity = value;
					if ((value != null))
					{
						value.Onerges.Add(this);
						this._KonuGrupID = value.ID;
					}
					else
					{
						this._KonuGrupID = default(Nullable<int>);
					}
					this.SendPropertyChanged("OnergeKonuGrupları");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnergeTuru_Onerge", Storage="_OnergeTuru", ThisKey="TurID", OtherKey="ID", IsForeignKey=true)]
		public OnergeTuru OnergeTuru
		{
			get
			{
				return this._OnergeTuru.Entity;
			}
			set
			{
				OnergeTuru previousValue = this._OnergeTuru.Entity;
				if (((previousValue != value) 
							|| (this._OnergeTuru.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OnergeTuru.Entity = null;
						previousValue.Onerges.Remove(this);
					}
					this._OnergeTuru.Entity = value;
					if ((value != null))
					{
						value.Onerges.Add(this);
						this._TurID = value.ID;
					}
					else
					{
						this._TurID = default(Nullable<int>);
					}
					this.SendPropertyChanged("OnergeTuru");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MilletVekili_Onerge", Storage="_MilletVekili", ThisKey="milletvekiliID", OtherKey="ID", IsForeignKey=true)]
		public MilletVekili MilletVekili
		{
			get
			{
				return this._MilletVekili.Entity;
			}
			set
			{
				MilletVekili previousValue = this._MilletVekili.Entity;
				if (((previousValue != value) 
							|| (this._MilletVekili.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MilletVekili.Entity = null;
						previousValue.Onerges.Remove(this);
					}
					this._MilletVekili.Entity = value;
					if ((value != null))
					{
						value.Onerges.Add(this);
						this._milletvekiliID = value.ID;
					}
					else
					{
						this._milletvekiliID = default(Nullable<int>);
					}
					this.SendPropertyChanged("MilletVekili");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mesajs(Mesaj entity)
		{
			this.SendPropertyChanging();
			entity.Onerge = this;
		}
		
		private void detach_Mesajs(Mesaj entity)
		{
			this.SendPropertyChanging();
			entity.Onerge = null;
		}
		
		private void attach_Cevaps(Cevap entity)
		{
			this.SendPropertyChanging();
			entity.Onerge = this;
		}
		
		private void detach_Cevaps(Cevap entity)
		{
			this.SendPropertyChanging();
			entity.Onerge = null;
		}
		
		private void attach_MesajAdmins(MesajAdmin entity)
		{
			this.SendPropertyChanging();
			entity.Onerge = this;
		}
		
		private void detach_MesajAdmins(MesajAdmin entity)
		{
			this.SendPropertyChanging();
			entity.Onerge = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MilletVekili")]
	public partial class MilletVekili : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _milletvekiliAdı;
		
		private System.Nullable<int> _sayac;
		
		private string _partisi;
		
		private string _ili;
		
		private EntitySet<Onerge> _Onerges;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnmilletvekiliAdıChanging(string value);
    partial void OnmilletvekiliAdıChanged();
    partial void OnsayacChanging(System.Nullable<int> value);
    partial void OnsayacChanged();
    partial void OnpartisiChanging(string value);
    partial void OnpartisiChanged();
    partial void OniliChanging(string value);
    partial void OniliChanged();
    #endregion
		
		public MilletVekili()
		{
			this._Onerges = new EntitySet<Onerge>(new Action<Onerge>(this.attach_Onerges), new Action<Onerge>(this.detach_Onerges));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_milletvekiliAdı", DbType="NVarChar(150)")]
		public string milletvekiliAdı
		{
			get
			{
				return this._milletvekiliAdı;
			}
			set
			{
				if ((this._milletvekiliAdı != value))
				{
					this.OnmilletvekiliAdıChanging(value);
					this.SendPropertyChanging();
					this._milletvekiliAdı = value;
					this.SendPropertyChanged("milletvekiliAdı");
					this.OnmilletvekiliAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sayac", DbType="Int")]
		public System.Nullable<int> sayac
		{
			get
			{
				return this._sayac;
			}
			set
			{
				if ((this._sayac != value))
				{
					this.OnsayacChanging(value);
					this.SendPropertyChanging();
					this._sayac = value;
					this.SendPropertyChanged("sayac");
					this.OnsayacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partisi", DbType="NVarChar(50)")]
		public string partisi
		{
			get
			{
				return this._partisi;
			}
			set
			{
				if ((this._partisi != value))
				{
					this.OnpartisiChanging(value);
					this.SendPropertyChanging();
					this._partisi = value;
					this.SendPropertyChanged("partisi");
					this.OnpartisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ili", DbType="NVarChar(50)")]
		public string ili
		{
			get
			{
				return this._ili;
			}
			set
			{
				if ((this._ili != value))
				{
					this.OniliChanging(value);
					this.SendPropertyChanging();
					this._ili = value;
					this.SendPropertyChanged("ili");
					this.OniliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MilletVekili_Onerge", Storage="_Onerges", ThisKey="ID", OtherKey="milletvekiliID")]
		public EntitySet<Onerge> Onerges
		{
			get
			{
				return this._Onerges;
			}
			set
			{
				this._Onerges.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.MilletVekili = this;
		}
		
		private void detach_Onerges(Onerge entity)
		{
			this.SendPropertyChanging();
			entity.MilletVekili = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MesajAdmin")]
	public partial class MesajAdmin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDM;
		
		private string _mesajKonusu;
		
		private System.Nullable<int> _kurumID;
		
		private System.Nullable<int> _onergeID;
		
		private System.Nullable<int> _okunma;
		
		private EntityRef<Kurum> _Kurum;
		
		private EntityRef<Onerge> _Onerge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMChanging(int value);
    partial void OnIDMChanged();
    partial void OnmesajKonusuChanging(string value);
    partial void OnmesajKonusuChanged();
    partial void OnkurumIDChanging(System.Nullable<int> value);
    partial void OnkurumIDChanged();
    partial void OnonergeIDChanging(System.Nullable<int> value);
    partial void OnonergeIDChanged();
    partial void OnokunmaChanging(System.Nullable<int> value);
    partial void OnokunmaChanged();
    #endregion
		
		public MesajAdmin()
		{
			this._Kurum = default(EntityRef<Kurum>);
			this._Onerge = default(EntityRef<Onerge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDM
		{
			get
			{
				return this._IDM;
			}
			set
			{
				if ((this._IDM != value))
				{
					this.OnIDMChanging(value);
					this.SendPropertyChanging();
					this._IDM = value;
					this.SendPropertyChanged("IDM");
					this.OnIDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesajKonusu", DbType="NVarChar(MAX)")]
		public string mesajKonusu
		{
			get
			{
				return this._mesajKonusu;
			}
			set
			{
				if ((this._mesajKonusu != value))
				{
					this.OnmesajKonusuChanging(value);
					this.SendPropertyChanging();
					this._mesajKonusu = value;
					this.SendPropertyChanged("mesajKonusu");
					this.OnmesajKonusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurumID", DbType="Int")]
		public System.Nullable<int> kurumID
		{
			get
			{
				return this._kurumID;
			}
			set
			{
				if ((this._kurumID != value))
				{
					if (this._Kurum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkurumIDChanging(value);
					this.SendPropertyChanging();
					this._kurumID = value;
					this.SendPropertyChanged("kurumID");
					this.OnkurumIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onergeID", DbType="Int")]
		public System.Nullable<int> onergeID
		{
			get
			{
				return this._onergeID;
			}
			set
			{
				if ((this._onergeID != value))
				{
					if (this._Onerge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnonergeIDChanging(value);
					this.SendPropertyChanging();
					this._onergeID = value;
					this.SendPropertyChanged("onergeID");
					this.OnonergeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_okunma", DbType="Int")]
		public System.Nullable<int> okunma
		{
			get
			{
				return this._okunma;
			}
			set
			{
				if ((this._okunma != value))
				{
					this.OnokunmaChanging(value);
					this.SendPropertyChanging();
					this._okunma = value;
					this.SendPropertyChanged("okunma");
					this.OnokunmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurum_MesajAdmin", Storage="_Kurum", ThisKey="kurumID", OtherKey="ID", IsForeignKey=true)]
		public Kurum Kurum
		{
			get
			{
				return this._Kurum.Entity;
			}
			set
			{
				Kurum previousValue = this._Kurum.Entity;
				if (((previousValue != value) 
							|| (this._Kurum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kurum.Entity = null;
						previousValue.MesajAdmins.Remove(this);
					}
					this._Kurum.Entity = value;
					if ((value != null))
					{
						value.MesajAdmins.Add(this);
						this._kurumID = value.ID;
					}
					else
					{
						this._kurumID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kurum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Onerge_MesajAdmin", Storage="_Onerge", ThisKey="onergeID", OtherKey="ID", IsForeignKey=true)]
		public Onerge Onerge
		{
			get
			{
				return this._Onerge.Entity;
			}
			set
			{
				Onerge previousValue = this._Onerge.Entity;
				if (((previousValue != value) 
							|| (this._Onerge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Onerge.Entity = null;
						previousValue.MesajAdmins.Remove(this);
					}
					this._Onerge.Entity = value;
					if ((value != null))
					{
						value.MesajAdmins.Add(this);
						this._onergeID = value.ID;
					}
					else
					{
						this._onergeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Onerge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
