package com.example.libraryautomation;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

public class AdminSubmit extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private Label labelUserName;
	private Label labelPassword;
	public AdminSubmit() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new HorizontalLayout();
		
		labelUserName=new Label();
		labelPassword=new Label();
		labelUserName.setImmediate(true);
		labelPassword.setImmediate(true);
		mainLayout.addComponent(labelPassword);
		mainLayout.addComponent(labelUserName);
		
	}

	public Label getLabelUserName() {
		return labelUserName;
	}

	public void setLabelUserName(Label labelUserName) {
		this.labelUserName = labelUserName;
	}

	public Label getLabelPassword() {
		return labelPassword;
	}

	public void setLabelPassword(Label labelPassword) {
		this.labelPassword = labelPassword;
	}

	

}
