package libraryprojepersontable;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;


public class PersonSubmit extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private Label labelName;
	private Label labelLastName;
	private Label labelPhoneNumber;
	private Label labelGender;
	private Label labelEmail;
	private Label labelPersonID;
	
	public PersonSubmit() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new HorizontalLayout();
		 labelName=new Label();
		 labelLastName=new Label();
		 labelPhoneNumber=new Label();
		 labelGender=new Label();
		 labelEmail=new Label();
		 labelPersonID=new Label();
		 
		 labelName.setImmediate(true);
		 labelLastName.setImmediate(true);
		 labelPhoneNumber.setImmediate(true);
		 labelGender.setImmediate(true);
		 labelEmail.setImmediate(true);
		 labelPersonID.setImmediate(true);
		 
			mainLayout.addComponent(labelName);
			mainLayout.addComponent(labelLastName);
			mainLayout.addComponent(labelPhoneNumber);
			mainLayout.addComponent(labelGender);
			mainLayout.addComponent(labelEmail);
			mainLayout.addComponent(labelPersonID);
		
	}

	public  Label getLabelName() {
		return labelName;
	}

	public void setLabelName(Label labelName) {
		this.labelName = labelName;
	}

	public Label getLabelLastName() {
		return labelLastName;
	}

	public void setLabelLastName(Label labelLastName) {
		this.labelLastName = labelLastName;
	}

	public Label getLabelPhoneNumber() {
		return labelPhoneNumber;
	}

	public void setLabelPhoneNumber(Label labelPhoneNumber) {
		this.labelPhoneNumber = labelPhoneNumber;
	}
	public Label getLabelGender() {
		return labelGender;
	}
	public void setLabelGender(Label labelGender) {
		this.labelGender = labelGender;
	}
	public Label getLabelEmail() {
		return labelEmail;
	}
	public void setLabelEmail(Label labelEmail) {
		this.labelEmail = labelEmail;
	}

	public Label getLabelPersonID() {
		return labelPersonID;
	}

	public void setLabelPersonID(Label labelPersonID) {
		this.labelPersonID = labelPersonID;
	}
	
}
